# Task 1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, transform, img_as_float

In [ ]:
# define a numpy array of length 10, put random values
x = np.array([1, 6, 4, -2, 9, 12, 2, 4, 3])

# select a slice with the even numbers
x_even = None

# select a slice with even indexed numbers
x_even_idx = None

# print the even indexed numbers in reverse order
print(None)

# Task 2

In [ ]:
x = np.array([[1, 2, 3, 4, 5], [0, 1, 2, 3, 4], [-1, 2, 5, 1 , 0]])

# print the submatrix with even indexed rows and odd indexed columns
# should print [[2, 4], [2, 1]]
print(None)

# flip the matrix by 180 degree
# should print [[0, 1, 5, 2, -1], [4, 3, 2, 1, 0], [5, 4, 3, 2, 1]]
print(None)

None
[[ 0  1  5  2 -1]
 [ 4  3  2  1  0]
 [ 5  4  3  2  1]]
None


# Task 3

In [ ]:
# import the cat image
I = None

# normalize the image between 0 and 1
I_norm = None

# crop only the cat's face and imshow it
I_cropped = None